# Basic Information 
title: LIU Xiangrui
position: Ph.D. Candidate
affiliation: City University of Hong Kong
affiliation_link: https://www.cityu.edu.hk/
affiliation_logo: ./assets/img/cityu_logo.png
email: xiangrliu3-c (at) my.cityu.edu.hk

# Search Engine Optimization (SEO)
keywords: liu xiangrui
description: LIU Xiangrui's personal blog
canonical: https://liuxiangrui.github.io//

# Links 
google_scholar: https://scholar.google.com/citations?user=yLyiy2UAAAAJ/
github_link: https://github.com/LiuXiangrui/
orcid: https://orcid.org/0000-0002-3300-6287
linkedin: https://www.linkedin.com/in/xiangrui-liu-643250262/

# Images (e.g., your profile picture and your website's favicon) 
avatar: /assets/img/avatar.jpg
favicon: /assets/img/monkey.png

# Footnote ("Powered by Jekyll and Minimal Light theme.")
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
